name: docker-easy-haproxy

project:
  version: 1.0.0
  download_url: https://github.com/byjg/docker-easy-haproxy/releases

license:
  software: MIT
  software_url: https://opensource.org/licenses/MIT
  
  docs: MIT
  docs_url: https://opensource.org/licenses/MIT
  
git_edit_address: https://github.com/byjg/docker-easy-haproxy/blob/master/

links:
  header:
  - title: GitHub
    url: https://github.com/byjg/docker-easy-haproxy
  - title: ByJG
    url: https://opensource.byjg.com/
  footer:
  - title: GitHub
    url: https://github.com/byjg/docker-easy-haproxy
  - title: Issues
    url: https://github.com/byjg/docker-easy-haproxy/issues

ui:
  header:
    color1: "#080331"
    color2: "#0033cc"
    trianglify: true

social:
  github:
    user: byjg
    repo: docker-easy-haproxy
  twitter:
    enabled: false
    via: 
    hash: opensourcebyjg
    account: 
  facebook:
    enabled: true
    url: https://opensource.byjg.com/
    profileUrl:

author:
  twitter: byjg

twitter:
  card: summary
  username: byjg

logo: https://opensource.byjg.com/images/logo_byjg.png

analytics:
  google: UA-130014324-1

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
remote_theme: byjg/jekyll-docs-theme

